stellar/starlight

specifications/sep-payment-channel-mechanism.md
Add a SEP that defines the transactions required to form a payment channel, using the new preconditions in CAP-21, and based on the two-way payment channel in CAP-21's rationale section.
CAP-21 contains a brief description of how to use CAP-21's new preconditions to support a two-way payment channel protocol, but there are more things that participants need to agree on in regards to the transactions and blockchain state. We should document all these things in a new SEP.
We can work on and iterate on the SEP in this repo for the moment until we have prototyped it and have some confidence we want to propose it as a SEP in the stellar-protocol repository.
This SEP contains no discussion of a transport protocol because it is out-of-scope. We aren't at a point where it is really important to …
=> Add SEP defining transactions required

specifications/sep-payment-channel-mechanism.md
Make changes to the SEP so that it uses two escrow accounts and no claimable balances.
See stellar/stellar-protocol#938 for why.
=> Change the SEP to use two escrow accounts

specifications/sep-payment-channel-mechanism.md
Remove statement about CAP-23 from the SEP.
CAP-23 is no longer used by the SEP. It was in a prior version but is no longer.
=> SEP: Remove obsolete statement about CAP-23

specifications/sequence-diagrams/README.md, specifications/sequence-diagrams/withdraw.txt
adds a sequence diagram going through the [withdrawal steps](https://github.com/stellar/experimental-payment-channels/blob/main/specifications/sep-payment-channel-mechanism.md#withdraw) of the payment channel SEP
=> specifications/sequence-diagrams: add withdraw seq diagram

specifications/sep-payment-channel-mechanism.md
Add change trust operations to the formation transaction.
Even though the escrow accounts will likely have all the trustlines required because the setup step involves adding the initial contributions, it is still really important that the change trust operations exist in the formation transaction otherwise an asset with a zero balance in either account but that the closing transaction will disburse could leave the channel in a broken state. A participant could remove a trustline just before the formation transaction is executed. The responder could do this undetected because their escrow accounts sequence number has no bearing on the formation transaction.
I removed the trustlines in 5b8afc1fbe195ab7032c08eb798d84f2cdb30fbb but overlooked this issue.
=> SEP: Add change trust ops to formation

README.md
Add note to README indicating that the Go SDK fork is in the same place as the Horizon fork.
It isn't clear to others where it lived.
=> Add note about Go SDK fork

specifications/sep-payment-channel-mechanism.md
Move the building of the formation transaction to after the first close and declaration transactions are signed and exchanged.
It was only built first because the formation transaction's sequence number was defined as `s_i`, but there is only ever one formation transaction, and it is always `s_0`, so it can be defined simply as `s` and it can be built after `C_i` and `D_i`. This makes the process simpler both to understand, and to reduce in implementations since the agreement about the initial state can be entirely independent of the formation step.
=> SEP: Simplify the steps during setup

sdk/txbuild/formation.go, specifications/sep-payment-channel-mechanism.md
ensure the other party is a signer and has an equal weight for each escrow account. This ensures the Escrow account is in the right state for the channel, w/o relying on the other party to do it correctly themselves
=> in formation transaction ensure other party is signer and weight of 1

.github/workflows/sdk.yml, examples/02-using-go-sdk/participant.go, sdk/go.mod, sdk/txbuild/create_escrow.go, sdk/txbuild/test_test.go
Add a test to the sdk that tests the existing tx building functions against a running CAP-21 forks of Horizon and Core.
So that we can ensure we maintain some stability and basic behavior as we're experimenting and starting to build out the API.
The test is a high-level integration test because unit tests for tx building would likely involve building the tx in the test and in the code and checking they are equal, which is not particularly useful at this stage.
=> sdk: add test

sdk/go.mod, sdk/go.sum, sdk/txbuild/close.go, sdk/txbuild/create_escrow.go, sdk/txbuild/declaration.go, sdk/txbuild/formation.go, sdk/txbuild/test_test.go
Set the fee to zero in txbuild built transactions, and require the use of fee bumps by a participant when submitting a tx.
The SEP specifies that fee bumps should be used. The reason is to keep the balances of the escrow accounts unaffected be fees which makes accounting simpler.
Close #36
=> sdk: use fee bumps

README.md
Add the `extraSigners` precondition to the list of CAP-21 preconditions in the README that are not implemented in the forks.
The `extraSigners` precondition was added to CAP-21, and wasn't included in the list here. Adding to the list in the README so it is clear whether that precondition is currently implemented in the forks and in the channels implemented in this repo at this moment.
=> readme: add extraSigners to list of CAP-21 preconditions

specifications/sep-payment-channel-transactions.md
Rename the SEP title so as to scope the SEP to specifying the transactions and how they are used.
We will no doubt write other SEPs that discuss coordination, networking, messaging, or refer to other external specifications for those things. It is helpful to scope this SEP from the get-go so it is clear what its current scope is.
=> sep: rename sep to scope to transactions

sdk/go.mod, sdk/go.sum, sdk/state/state.go
Add helpers for signing and verification, and switches to storing internals of the channel state in the form of local/remote, and adds helper functions for getting at that data from the initiator/responder viewpoint.
This is a break out of some functionality in #52 that @acharb will probably be able to use while working on #46.
The reason to change the internals to be local/remote focused instead of initiator/responder is because signing keys will be different types for local vs remote, since the local will be a full key and remote will be only an address. So, this keeps all the internals in local/remote perspective.
=> sdk: add helper sign and verify funcs and use local/remote terms

sdk/state/state.go, sdk/state/state_test.go, sdk/state/update.go
store the lastConfirmedPayment on the channel, and evaluate balances based off of that payment
also, removes the json marshalling/unmarshalling from the test to simulate the handoff. More trouble than it's worth
fulfills part of https://github.com/stellar/experimental-payment-channels/issues/63, but not the iteration part. Going to do that in separate PR
=> sdk: store lastPayment on channel  and evaluate balance from there 

sdk/state/state.go, sdk/state/state_open.go, sdk/state/state_test.go, sdk/state/update.go
Add fully signed param to confirm functions that indicates if the value being returned is completely signed and valid for submission if the user wished to submit the transactions to the network. Also, the error value of the confirm functions no longer error when the value is not completely signed, and no other error occurred.
@acharb mentioned it was confusing that the functions returns values that would be usable when returning an errors. I also found it difficult to remember that the errors returned from these functions could be catastrophic, but then also just routine part of how the process works.
It's a bit more verbose but clearer if the function returns some solid signal that this is fully signed, or complete and submittable, separate to whether some other arbitrary error occurred. …
=> sdk/state: add fully signed param to confirm functions

sdk/state/state.go, sdk/state/state_open.go, sdk/state/state_test.go, sdk/state/update.go
removes `c.SetIterationNumber`. The channel's current iteration number = lastCloseAgreement.IterationNumber + 1
note:
- not updating `lastUnconfirmedPayment` yet. So adding the field as a dummy field for when it's added
closes https://github.com/stellar/experimental-payment-channels/issues/64 and https://github.com/stellar/experimental-payment-channels/issues/61
=> sdk/state: move iteration to be pulled from latestCloseAgreement

sdk/state/state.go, sdk/state/state_open.go, sdk/state/state_test.go, sdk/state/update.go, sdk/state/update_test.go
this stores the latestUnconfirmedPayment on the channel, and uses it for validation in `ConfirmPayment`
This is to prevent the case of a receiver receiving two payments with different data but using the same next iteration number.
Also adds a unit test to test this
closes https://github.com/stellar/experimental-payment-channels/issues/69
=> sdk/state: store latestUnconfirmedPayment, add unit test

sdk/state/close.go, sdk/state/open.go, sdk/state/update.go, sdk/state/update_test.go, sdk/txbuild/close.go, sdk/txbuild/formation.go, sdk/txbuild/test_test.go
this is the core change for [this ticket](https://github.com/stellar/experimental-payment-channels/issues/71) of supporting non-native currencies.
Steps in this PR:
(basically the initial changes in `txbuild`, which will be used by `sdk/state`)
1. change txbuild/close to create a closing channel transaction that has payments in non-native asset.
2. change txbuild/formation to configure the channel to support non-native asset
Next steps (not in this PR):
1. Escrow account creation needs trustlines for non-native assets
2. Change the open channel functionality to be able to custom choose a non-native asset
2. The `latestCloseAgreement` `lastUnconfirmedPayment` need to store what the channel asset is
3. When closing the channel the payments need to be able to be non-native assets
=> sdk/state: form channel and close channel with non-native currency

sdk/state/integration/helpers_test.go, sdk/state/integration/state_test.go, sdk/txbuild/create_escrow.go, sdk/txbuild/test_test.go
escrow accounts supporting non-native assets. Currently escrow accounts are for xlm only. This changes that
In order to test this there needed to be changes done in the test files. Comments point out where
closes part of [this ticket](https://github.com/stellar/experimental-payment-channels/issues/71)
=> sdk/state: add support for non-native assets in the escrow accounts

sdk/state/integration/state_test.go, sdk/state/open.go, sdk/state/open_test.go, sdk/state/state.go, sdk/state/update.go, sdk/state/update_test.go
this is the final changes for supporting non-native assets.
1. Changes the Open functions to take asset type as an input, so that we can create channels with non-native
2. Changes the Update functions to support non-native
3. Add non-native functionality to tests
(note the closing functions are already supporting non-native from previous PRs)
=> sdk/state: finish adding non-native asset support

sdk/state/open_test.go
Small changes to the `TestProposePayment_valid_asset` test:
- Rename to `TestProposePayment_validAsset`.
- Change the setup of the invalid asset test so that a valid asset limit is provided.
- Use EqualError instead of separate Error and Equal assertions.
Camel case for test descriptions is more common after the first underscore that separates the test entity from the description.
The invalid asset test had an invalid asset limit so it was testing the same thing as the invalid asset limit test and not actually testing that invalid assets provided to the function will be caught.
We can use EqualError to check that an error occurred and that its error string matches the given value.
=> sdk/state: fix TestProposePayment_validAsset test

sdk/state/update.go
Replace `errors.New(fmt.Sprintf(...))` with `fmt.Errorsf(...)`.
One of the default Go linters that are configured in VSCode is warning about it.
=> sdk/state: fix linter errors

.github/workflows/sdk.yml, sdk/state/integration/helpers_test.go, sdk/state/integration/state_test.go, sdk/state/update.go, sdk/txbuild/test_test.go
Add golangci-lint linter to run on PRs.
To get some of the basic lint checks that we use in other repos, like staticcheck, to reduce warnings that some IDEs like VSCode will display when viewing the code in this repo.
We don't actually use golangci-lint in the stellar/go repo, but it is a popular and simple way to run a variety of linters including staticcheck, and if it goes well here I think I'll propose we replace staticcheck there with it too.
=> sdk: add golangci-lint ci run

sdk/txbuild/close.go, sdk/txbuild/declaration.go
Remove the todo comment saying we need to make the time bounds explicit.
Channels are long lived and we actually want the closes to be valid for a long time, indefinitely. There's no need to restrict the window within which they are valid. We're using the new relative bounds mechanisms introduced in CAP-21 to limit when they can be executed instead.
=> sdk/txbuild: remove comment about time bounds

sdk/state/close.go, sdk/state/state.go, sdk/state/update.go, sdk/state/update_test.go
adds functionality for merging new signatures into stored signatures instead of overwriting. This process is done in the close and update steps, when a user receives signatures from the other party and needs to store them locally
closes https://github.com/stellar/experimental-payment-channels/issues/82
=> sdk/state: merge new signatures into stored signature slice instead of overwriting

sdk/state/close.go, sdk/state/integration/state_test.go, sdk/state/state.go, sdk/state/update.go, sdk/state/update_test.go
from [this comment](https://github.com/stellar/experimental-payment-channels/pull/83#discussion_r657387696) I removed `CoordinatedClose` and changed `channel.latestUnconfirmedPayment` to `channel.latestUnconfirmedCloseAgreement`. 
In doing so it became apparent we don't need the `Payment` struct, and can just pass around / store a `CloseAgreement` 😄 . So made those changes here
=> sdk/state: use CloseAgreement instead of Payment and CoordinatedClose structs

sdk/state/close.go, sdk/state/open.go, sdk/state/state.go, sdk/state/update.go, sdk/state/update_test.go
Make the `CloseAgreement` fields that define what the agreement is, comparable.
In some places we're wanting to compare if two close agreements are the same and we are using a function, isEquivalent, to find out. This works, but there are some advantages to us using simple Go value comparisons for this and we can use them if we group the fields that define the details or term of the agreement together:
- The data structure communicates what parts of the agreement make up the actual agreement vs sigs.
- We can use the agreement details as map keys if we need to.
- It makes copying an agreement independent of signatures simpler.
- This follows the same pattern Stellar transactions use.
Close #105
=> sdk/state: make close agreement details comparable

sdk/state/close.go, sdk/state/integration/state_test.go, sdk/state/open.go, sdk/state/state.go, sdk/state/update.go, sdk/state/update_test.go
Use authorized and unauthorized language to refer to close agreements that have been signed by all participants or not.
The code uses two terms `fullySigned` and `unconfirmed` to refer to if a close agreement is respectively authorized or unauthorized. It's unhelpful we use two terms that aren't clearly opposites of one another as the reader must have this tribal knowledge or infer it from logic in the SDK. It would be helpful to use a single term that have simple opposites. Unfortunately `fullySigned` is not a great choice because `notFullySigned` is long and wordy. Unfortunately `unconfirmed` is not a great choice because `confirmed` is an ambiguous term to use given the `ConfirmX` functions in the SDK do not result in a completely confirmed agreement, but in many cases a partially …
=> sdk/state: use authorized/unauthorized language

sdk/state/update.go
Remove use of strconv in fmt strings that can be done with `%d`.
It's the common way to include numbers in strings, and is simpler.
=> sdk/state: remove unnecessary use of strconv

sdk/state/integrationtests/helpers_test.go, sdk/state/integrationtests/state_test.go, sdk/state/open.go, sdk/state/open_test.go, sdk/state/update.go, sdk/txbuild/create_escrow.go, sdk/txbuild/formation.go
Change the asset limit to be an int64 to be consistent with the Amount Balance being stored as an int64.
For consistency, so all amounts are stored the same way. This also makes it easier to work with the value since we can use simple math operations on it if we need to.
=> sdk/state: keep amounts in int64

sdk/state/integrationtests/helpers_test.go, sdk/txbuild/integrationtests/helpers_test.go, sdk/txbuild/integrationtests/integrationtests_test.go
Move integration test helpers into a `helpers_test.go`.
@acharb introduced this pattern in the `state` package and it has worked pretty well in that package.
This PR contains commits from #115 that should disappear once that PR is merged.
=> sdk/txbuild: move integration test helpers into another file

sdk/state/integrationtests/helpers_test.go, sdk/state/integrationtests/state_test.go
Move the `assetBalance` helper function into the `helpers_test.go`.
It seems to be where our other helpers have landed.
=> sdk/state: move helper test function into helpers file

sdk/state/close.go, sdk/state/integrationtests/state_test.go, sdk/state/state.go, sdk/state/update.go
Consolidate the building of close transactions so that there is only one function and one place that occurs.
Building the close transactions happens in three places currently, in `CloseTxs`, `PaymentTxs`, and in `ProposePayment`. Each location collect the input data in different ways. There should be one owner responsible for close tx building. Ideally we are always building close txs during the update or final steps the exact same way.
For #127, although does not resolve it completely.
This PR should be merged after #130.
=> sdk/state: consolidate the building of close txs

sdk/state/close.go, sdk/state/integrationtests/helpers_test.go, sdk/state/integrationtests/state_test.go, sdk/state/open.go, sdk/state/state.go, sdk/state/update.go, sdk/state/update_test.go
Remove `CoordinatedCloseTxs` and build the observation parameters into the `ClosingAgreement`.
Coordinated close is the happy path and so we should make it the default way to close, with closing without the additional signatures being the fallback. There's a few changes we need to make for this to happen, and this is the first, that there aren't separate functions, like `CoordinatedCloseTxs` for getting the coordinated closing transaction. The user should be able to just get the closing transactions, via `CloseTxs`, and if the agreement is a coordinated close agreement, it should just work.
There was another reason we were thinking of moving observation parameters into the closing agreement, but I don't remember what they were.
Related to #127 
This should be merged after #131 and …
=> sdk/state: remove CoordinatedCloseTxs and build observation into closing agreements

sdk/state/state.go
Remove code not be used.
It isn't being used, and I don't think we'll use it.
=> sdk/state: remove code not being used

sdk/state/close.go, sdk/state/integrationtests/state_test.go
Remove the term `Coordinated` from function names and code.
The default happy path is to do a coordinated close, or rather, it should just be part of the standard close process which involves declaring, trying to coordinate the immediate close, and falling back to using the existing close transactions. While we call this coordinated close in the SEP, I don't think we get much value of using the term in the SDK because in practice there will be one close process not two.
=> sdk/state: remove Coordinated term from func names

sdk/state/integrationtests/helpers_test.go, sdk/state/integrationtests/state_test.go, sdk/state/open.go, sdk/state/open_test.go, sdk/txbuild/create_escrow.go, sdk/txbuild/formation.go, sdk/txbuild/integrationtests/integrationtests_test.go
supports multiple assets when forming the accounts (`txbuild/formation`, `txbuild/create_escrow`) and in the open steps
(`state/open`)
After this PR will add support in the rest of the code (`close` and `update` steps)
Fulfills part of https://github.com/stellar/experimental-payment-channels/issues/72
=> sdk/state, sdk/txbuild: support multiple assets when forming and opening accounts 

sdk/state/update.go, sdk/state/update_test.go
Change the `ConfirmPayment` function so it rejects payments from the remote if the remote is proposing that the local pay the remote.
This is a payment channel where either party can send money to the other party, and it isn't designed fro requesting/invoicing the other party for funds. There's several reasons for this. It is safer and easier to write confirm functionality that enforces this rather than require that the user always check the balance is an okay change. The channel is designed to always move forward and in disagreement it becomes unclear if the channel should close or stay open and skip a generation. Mostly this is for simplicity for the major use case.
Close #112
=> sdk/state: reject payments from remote if they change balance in their favor

specifications/sep-payment-channel-transactions.md
with two escrow account setup the Balance at the beginning of the channel is 0. so C_1 doesn't send out disbursements, just closes the channel
=> specifications: fix setup sentence in SEP

specifications/sep-payment-channel-transactions.md
Change the number of assets a single payment channel can hold to one.
I'm discussions we realized multiple assets are unnecessary at this stage because we aren't targeting swap/exchange use cases. We're targeting payments only. For payments participants can open multiple channels, one for each asset.
Close #144
=> sep: support single asset only

specifications/sep-payment-channel-transactions.md
Restrict the trustline limit that non-native assets use to the max.
To simplify the protocol. See the change for more details.
Close #145
=> sep: add notes about trustline limit

sdk/state/integrationtests/helpers_test.go, sdk/state/integrationtests/state_test.go, sdk/state/open.go, sdk/state/open_test.go, sdk/txbuild/create_escrow.go, sdk/txbuild/formation.go, sdk/txbuild/integrationtests/integrationtests_test.go
Change the SDK back to supporting a single asset only.
We resolved to focus on single asset payment channels because someone made a good point that if we aren't supporting exchange/swaps, then there isn't huge value in having multiple assets in the one channel vs multiple single-asset channels.
Incorporates the changes proposed by SEP changes #146 and #147.
Close #72
=> sdk/state: support single asset only

sdk/state/asset.go, sdk/state/asset_test.go, sdk/state/close.go, sdk/state/integrationtests/helpers_test.go, sdk/state/integrationtests/state_test.go, sdk/state/open.go, sdk/state/open_test.go, sdk/state/state.go, sdk/state/update_test.go
Replace txnbuild.Asset in the state package with an internal simpler asset type, a string that follows [SEP-11 Txrep]'s format.
While experimenting with the state package (#122) I found the interface type txnbuild.Asset inconvenient. Interfaces can't be used to deserialize. While working around that issue I realized we don't really need an interface for what we're doing, we only need a simple value and it is more convenient to be able to specify a concrete value in the simplest form and to convert it to what the txnbuild package needs at the point it needs it.
I chose a string because we have a specification for assets as string in [SEP-11 Txrep] which has been used in Horizon for new endpoints that reference assets.
[SEP-11 Txrep]: https://stellar.org/protocol/sep-11
=> sdk/state: replace txnbuild.Asset with an internal simpler asset type

sdk/txbuild/formation.go, specifications/sep-payment-channel-transactions.md
Make the participants sponsor only their own signers.
The SEP states that the participants are only supposed to sponsor their own signers, but then the open process has them sponsoring each other signers. This has little impact on single signer setups, but cleaning this up makes it a bit more pure on ownership of the respective ledger entries.
Close #151
=> sep, sdk/state: fix sponsorship operations during open

sdk/state/integrationtests/helpers_test.go, sdk/state/integrationtests/state_test.go, sdk/state/open.go, sdk/state/open_test.go, sdk/state/state.go, sdk/txbuild/formation.go, sdk/txbuild/integrationtests/integrationtests_test.go
Make the formation transaction that gets built deterministic by changing the time bounds to be based on time.Now to be based on a fixed time the proposer chooses.
The formation transaction sets its time bounds relative to the now time, which requires both participants to have synchronized clocks at a resolution of 1 second and for the clients to generate the transaction at the exact moment. This is unlikely to happen. This behavior also makes it impossible to regenerate the formation transaction later.
I discovered this problem while working on #122. Two participants running separately were producing different open agreement transactions because the time bound maximum was set to different values in the formation transaction.
Close #150
=> sdk/state: make formation expiry deterministic

sdk/state/close.go, sdk/state/integrationtests/state_test.go, sdk/state/open.go, sdk/state/state.go, sdk/state/update.go, sdk/state/update_test.go
Remove assets from `CloseAgreements` and some other places.
In #72 we rewound support for multiple assets and moved forward with single asset support only. `CloseAgreements` only need to include asset information if the channel is multi-asset. This simplifies several things. 
I realized this could be simplified when I worked on #155. In that change I needed to add a balance to `EscrowAccount`. It was going to be significantly harder to follow the existing pattern and include asset information in that object, so I didn't. I think it is worth bringing the same simplicity to close agreements and everywhere else.
=> sdk/state: remove assets from places only needed for multi asset support

sdk/go.mod, sdk/go.sum, sdk/state/close.go, sdk/state/integrationtests/state_test.go, sdk/state/state.go, sdk/state/update.go, sdk/state/update_test.go
When receiving a proposed new close agreement/payment, error with `ErrUnderfunded` if the close agreement over commits the payer. Support updating the known balances of escrow accounts so the payment can be confirmed if on network the balance has been increased.
The state machine does not validate that a proposed close agreement will be satisfied by the balance of the paying participant's balance. This is a problem because the payer could over commit, breaking the channel. The receiver in a payment shouldn't accept a close agreement if it can't be satisfied by the current balances in the escrow accounts.
It's possible for participants to deposit more of an asset into their escrow account, so it should also be possible 
to update the known balances inside the channel when that happens. …
=> sdk/state: validate balances and handle deposits and balance changes

sdk/state/state.go, sdk/state/update.go, sdk/state/update_test.go
Prevent a participant from proposing a payment that would exceed the balance they supplied to the payment channel.
@acharb pointed out (https://github.com/stellar/experimental-payment-channels/pull/155#discussion_r667233215) that allowing a participant to propose a payment too large could break the payment channel for both participants because the payment in the closing transaction would fail with insufficient funds. This isn't good for either participant. It also makes little sense to allow a payment to be proposed if a sensible other participant will reject it, which they should.
Close #157
=> sdk/state: prevent proposing payment that over commits

README.md
Add links to discussions.
So they are discoverable.
=> readme: add links to discussions

sdk/state/state.go
Export the initiator variable from the Channel.
The caller already knows about it since they choose who the initiator is during config, and it is helpful in picking who should take the first action in some processes like the open process. We might remove this later on to hide the notion of initiator, but for now having it is useful.
Something I discovered working on #122.
=> sdk/state: export initiator from Channel

sdk/go.mod, sdk/go.sum, sdk/state/open.go, sdk/state/open_test.go, sdk/state/payment.go, sdk/state/payment_test.go, sdk/state/state.go
Add some functions that I've found helpful:
- Equal functions on agreements.
- Functions to get the escrow account objects from the channel.
It's helpful for the user to be able to compare agreements to know if an agreement they have is the same as a new agreement.
It's helpful to be able to access the full state of the escrow account as known by the channel, and not just the balance that we expose now.
I discovered this while working on #122.
Close #175 
I shortcutted writing the equals methods by using the cmp.Equal package. We should really write a proper equals package that doesn't use reflection under the surface, but this should be sufficient for now.
=> sdk/state: add some helpful funcs

sdk/state/open_test.go, sdk/state/payment_test.go
Add a test case for open and close agreement equality functions that check if the signatures are different the function returns false.
@acharb pointed out that the tests were not actually testing that case because of a mistake in the last test cases. 
https://github.com/stellar/experimental-payment-channels/pull/177/files#r671552880
Close #175
=> sdk/state: fix test

sdk/state/close.go, sdk/state/close_test.go, sdk/state/integrationtests/state_test.go, sdk/state/open.go, sdk/state/open_test.go, sdk/state/payment.go, sdk/state/payment_test.go, sdk/state/state.go
Refactor the open and close tx functions so that they are no longer exported, focus solely on the txs they needs to generate, and add new open and close tx functions that are exported and intended to be used by a user wanting to submit those transactions.
While working on #122 it became clear that the example code had to know how to get an agreement and a transaction and get the transaction into a state that was ready for submission. This is something the state machine can really take ownership of. I think this improves the API.
As an example of how it improves the API take a look at the integration tests where there are many lines of code deleted.
=> sdk/state: refactor the open/close tx funcs

sdk/state/close.go, sdk/state/open.go, sdk/state/open_test.go, sdk/state/payment.go, sdk/state/payment_test.go
**WHAT**
move `Confirm<open,payment,close>` validation code to their own `validate<open,payment,close>` methods
**WHY**
now that the validation code is growing it makes sense to move to their own methods. This helps with both readability and with unit testing that validation code
this refactoring made sense while working on: https://github.com/stellar/experimental-payment-channels/issues/142
=> sdk/state: move validation code to own methods

specifications/sep-payment-channel-transactions.md
Add a space between sentences.
@acharb pointed out this typo in https://github.com/stellar/experimental-payment-channels/pull/162#discussion_r675081613 but the PR was auto-merged before it could be fixed.
=> sep: fix typo

sdk/state/close.go, sdk/state/payment.go
**WHAT**
in close and payment check that the given close agreement doesn't have a nil `ConfirmingSigner` before checking it
**WHY**
otherwise the check throws a runtime error if the other party gives you a close agreement with an empty `ConfirmingSigner`
ran into this while working on https://github.com/stellar/experimental-payment-channels/pull/197
=> sdk/state: check ConfirmingSigner isn't nil

sdk/state/payment.go, sdk/state/payment_test.go
**WHAT**
in ProposePayment and ConfirmPayment check to see if there's an accepted coordinated close , and if so don't allow new payments
**WHY**
with a fully signed coordinated close a participant could submit a C_i/D_i near instantly, which invalidates later payments
closes https://github.com/stellar/experimental-payment-channels/issues/107
=> sdk/state: reject payment if a coordinated close already accepted

sdk/state/open.go, sdk/state/payment.go
Use the new Equal funcs that were added to the keypair package in the stellar/go repo for comparing keypairs.
To simplify difficult to read code.
=> sdk/state: simplify some equal funcs using new stellar/go funcs

sdk/state/close.go, sdk/state/payment.go
Use keypair.Equal in more places rather than do manual comparisons.
I updated how we compare keypairs in some places in #205 and missed these other two places.
Note that the keypair.Equal function safely handles the case when the left-hand-side or right-hand-side are nil, so there is no need for the nil checks anymore either.
=> sdk/state: use keypair Equal in more places

sdk/state/close.go, sdk/state/close_test.go, sdk/state/integrationtests/state_test.go, sdk/state/open.go, sdk/state/open_test.go, sdk/state/payment.go, sdk/state/payment_test.go, sdk/state/state.go
Refactor how signatures are stored:
- Store the raw signature and not a decorated signature, not storing the hint.
- Store signatures in fields named for their purpose, rather than in a slice.
- Verify and sign in a single block, rather than piece meal.
Signatures were stored as decorated signature lists because early on it made it simple to add those signatures to a transaction at a later point. That optimization has made it painful to make several changes over the last few weeks, the worst being the implementation of CAP-40 (#190, #189).
The only benefit we got from storing decorated signatures was to speed up looking up signatures in each slice, because we frequently need to only verify a single signature for a single signer. Besides the fact it is unnecessary for us to be optimizing …
=> sdk/state: refactor signatures

sdk/state/integrationtests/main_test.go
Make the Horizon URL that is used for integration tests configurable.
A lot of the time, including on CI, the URL being `localhost:8000` works fine. For those of us who use Docker and are hosting the quickstart image's port on the host port on Mac, we need it to be set to `host.docker.internal:8000`. Using an environment variable is a simple low effort solution to make it configurable.
=> sdk/state: make integration test horizon url configurable

sdk/state/ingest_test.go
Remove line of code that's result is unused and has no effect.
@marcelosalloum reported it in #204 but the PR was auto-merged before it could be fixed.
=> sdk/state: remove unused code in test

sdk/state/close.go, sdk/state/close_test.go, sdk/state/integrationtests/helpers_test.go, sdk/state/payment.go, sdk/state/payment_test.go
**WHAT**
error if the channel is trying to propose or confirm a payment or close if the channel is not open yet
**WHY**
a channel shouldn't be able attempt to propose/confirm a payment or close if the channel is not open yet. Although the methods would fail, checking explicitly prevents unexpected behavior.
closes https://github.com/stellar/experimental-payment-channels/issues/186
=> sdk/state: error if proposing or confirming a payment or close if channel is not open yet

sdk/state/open.go, sdk/state/open_test.go
**WHAT**
throw an error if a channel has already been opened (and is still open or closed), and trying to propose or confirm a new open.
Also adds a helper method `isFull` for checking if an openAgreement is fully signed, indicating it's submittable and the channel is considered open
**WHY**
explicitly defining that you can't open a channel that has already been opened prevents unexpected channel behavior
closes https://github.com/stellar/experimental-payment-channels/issues/223
=> sdk/state: reject new open proposal/confirm if channel is already open

sdk/state/close.go, sdk/state/payment.go, sdk/state/payment_test.go
**WHAT**
enforce that only one unauthorized close agreement can exist at a time
**WHY**
currently this edge case exists:
```
A proposes {ca1}
B confirms {ca1}, but doesn't send sigs back to A
A proposes {ca2}, B submits ca1, and A can't finish ca1 because proposing cleared the latest unauthorized
```
by enforcing that A cant propose a {ca2}, which clears its {ca1}, it prevents this edge case and protects A.
closes https://github.com/stellar/experimental-payment-channels/issues/103
note:
- if A wants to close the channel after {ca1}, A would need to do an uncoordinated close, as this change prevents them from proposing a coordinated close which would also clear its unfinished {ca1}.
=> sdk/state: enforce only one close agreement open at a time

examples/console/main.go, sdk/agent/agent.go
Split the `Close` function in two, so there is `DeclareClose` and `Close`, and make them asynchronous and responsible for a single task each, mostly. The `DeclareClose` is responsible for kicking off a close, that may or may not complete itself via negotiation in the background. The `Close` is responsible for submitting the final close tx after the observation period.
The `Open` and `Payment` functions both have a single responsibility to open and pay respectfully. They perform these operations asynchronously by kicking off the process and then having corresponding handlers handle the response from the other participant should they agree. Their use is rather predictable.
The `Close` function is more confusing about where its responsibility begins and ends. It kicks off a close, negotiates …
=> sdk/agent: make open/pay/close ops consistently async

specifications/sep-payment-channel-mechanics.md
Change the title of the SEP to refer to the mechanics of the payment channel rather than transactions.
The SEP contains a specification of the transactions and the basic mechanics required to form and maintain a payment channel safely, so it defines more than just the transactions. For this reason I wanted to drop the `transactions` from the title. However, the SEP doesn't define much about how coordination should occur and so it is not a sufficient SEP in its current form to be considered a specification of the entire payment channel. The scope of the SEP is really the bare minimum mechanics which can sit under a variety of applications.
=> sep: change title

specifications/sep-payment-channel-mechanics.md
Add discussion about the risks of queueing multiple payments by sending multiple payments to the other participant before they confirm each individually.
CAP-40 gives us a bonus benefit that participants can make multiple payments without waiting for the confirmation from teh receiver. Some future version of the protocol defined in the SEP could use that bonus and make it possible for participants to speed up and slow down independent of each other and be allowed to fall behind for a period or indefinitely. There is one side-effect and tradeoff to that though which is important to weigh with any implementation that uses it. I wanted to document it so that we didn't forget about it if we went all in on that approach in the future.
=> sep: add discussion about risks with queueing payments

sdk/agent/agent.go
Move the channel creation in the agent into the open process instead of happening as part of the hello process.
The agent creates the channel the moment the agent has the hello information from the other participant, but this is somewhat unnecessary, introduces stale data, and complicates the channel setup.
It is unnecessary because the agent doesn't need the channel until the open process begins.
Stale data may be introduced because at the moment the sequence number of the escrow accounts is needed to be known when initializing the channel, however it could have changed by the time the open starts and when the open starts is when it is required.
The channel setup is complicated when the channel is created early because channel creation records who the initiator is. This has required us …
=> sdk/agent: move channel creation into open process

sdk/state/state.go
Remove old todo.
The todo comment has been there for a while but isn't something we're likely to do soon. It's something we'll need when we do #49 but we can address how that is implemented when and if we come to it.
=> sdk/state: remove old todo

sdk/state/state.go
Move the `Config` and `NewChannel` type and function above the `Channel` type.
The type and function are the entry point to using the `Channel`, but they're buried below some other types and functions. Moving them to the top makes them easier to discover and matches how the same pattern in the `sdk/agent` package.
=> sdk/state: reorder funcs

sdk/agent/agent.go, sdk/agent/agent_test.go
Change the hello message handling so that multiple hellos are allowed as long as they contain the same data.
When restoring a channel using a snapshot the hello messages will be exchanged again for the new setup. The agent considers that an error. That should be allowed.
=> sdk/agent: fix reconnect

sdk/state/close.go, sdk/state/close_test.go, sdk/state/open.go, sdk/state/open_test.go, sdk/state/payment.go, sdk/state/payment_test.go, sdk/state/state.go
Replace the `CloseAgreement` and `OpenAgreement` prefixes on types with simply `Close` and `Open`.
Rename `CloseAgreementSignatures` to `CloseSignatures`.
Rename `CloseAgreementTransactions` to `CloseTransactions`.
Rename `OpenAgreementSignatures` to `OpenSignatures`.
Rename `OpenAgreementTransactions` to `OpenTransactions`.
As a follow up of the storing transactions work (#294) and as part of the work to make it easy for examples and experiments to store transactions as they occur in the channel I plan to move the `CloseAgreementTransactions` and `CloseAgreement` into some new type. There are quite a few types nested the term 'Agreement' has become a little meaningless as it seems like the word shows up in every type. I think it would be helpful to remove it from everywhere except the …
=> sdk/state: rename CloseAgreement(.+) to Close$1

examples/console/main.go, sdk/agent/agent.go, sdk/agent/agent_test.go, sdk/agent/events.go, sdk/msg/msg.go, sdk/state/close.go, sdk/state/close_test.go, sdk/state/ingest.go, sdk/state/ingest_test.go, sdk/state/integrationtests/state_test.go, sdk/state/open.go, sdk/state/open_test.go, sdk/state/payment.go, sdk/state/payment_test.go, sdk/state/state.go, sdk/state/state_test.go
Encapsulate stored transactions `CloseTransactions` inside `CloseAgreement`, and move most of what is already inside `CloseAgreement` inside `CloseEnvelope` which lives inside `CloseAgreement`.
An example of an agreement in the `state.Channel` `Snapshot` rendered as JSON with this change:
```json
"LatestAuthorizedCloseAgreement": {
"Envelope": {
"Details": {
"ObservationPeriodTime": 0,
"ObservationPeriodLedgerGap": 0,
"IterationNumber": 4,
"Balance": 490000000,
"PaymentAmount": 30000000,
"ProposingSigner": "GBFUR3LXINTVW74QKRL7T5WSPABUJORLFOOH22PXGQCCWCAV3SHCHCQN",
"ConfirmingSigner": "GB5NCO6I2ROUAF2V7CRIKXQPQ5B4RIOUACTXEARXJE3PNJTXYYTONEX3"
},
"ProposerSignatures": {
"Close": "XGTZ/GzUEZf0vofMXun/R0fqBwrENGGJGev/dW3ZGHYE9q1r2eMAuGAUNdkFtM1QiNd9Hvu58imk3+i3x1f+AA==",
"Declaration": …
```
=> sdk/state: encapsulate stored txs inside close agreements

sdk/state/ingest.go, sdk/state/ingest_test.go
**WHAT**
if the channel ingests a transaction that would set the initiator escrow account seq num backwards, then return the ingestion process early and don't update state.
**WHY**
it can't be certain that transaction will be ingested in order in case two are submitted at the same time. So always just update the state from the transaction with the latest sequence number
closes https://github.com/stellar/experimental-payment-channels/issues/267
=> sdk/state: dont let escrow account sequence number go backwards

sdk/state/ingest.go, sdk/state/ingest_test.go, sdk/state/state.go
**WHAT**
end the IngestTx process early and return error if the channel hasnt been opened or has been closed
**WHY**
if the channel doesn't exist it shouldnt be updating its state
closes https://github.com/stellar/experimental-payment-channels/issues/282
=> sdk/state: in IngestTx end early if channel is closed or hasn't been opened

sdk/agent/agent.go, sdk/state/ingest.go, sdk/state/integrationtests/state_test.go, sdk/state/state.go
**WHAT**
OpenAgreement() to return OpenAgreement
LatestCloseAgreement() to return CloseAgreement
**WHY**
currently they're returning envelopes, which work but is confusing with the function name since there are also agreement types for those envelopes
=> sdk/state: have the exported funcs return agreements not envelopes

sdk/state/close.go, sdk/state/open.go, sdk/state/payment.go, sdk/state/state.go
Avoid rehashing transactions.
We rehash transactions during signing and verification. It's pretty expensive because full transaction has to be serialized. We hold hashes of the transactions next to the transactions and so there's little value in rehashing.
I didn't add any benchmark tests because even without benchmarks this is a pretty clear win that we wouldn't recalculate the hash when it is literally sitting next to the transaction in the same struct.
Close #327
=> sdk/state: avoid rehashing txs and remove cmp usage

sdk/state/close_test.go, sdk/state/open_test.go, sdk/state/payment_test.go
Add more tests covering signature checks of open, payment, and close agreements.
There weren't any tests covering this area of code.
=> sdk/state: add tests coverage for signature checks

sdk/state/payment.go, sdk/state/payment_test.go
Allow proposing payments with zero amounts.
The SDK prevents proposing payments that are zero amounts, but from best I can tell allows the receiver to accept a zero amount. It's not really necessary that we prevent zero payments and they can be a useful primitive for generating a new iteration for the current agreement.
This would make merging channels easier, and implementing turn taking buffered channels easier also.
Close #341
=> sdk/state: allow proposing payments with zero amounts

.github/workflows/examples-benchmark.yml
Add a ci job that makes sure the examples/benchmark code still compiles.
It isn't covered by the existing jobs.
=> examples/benchmark: add ci that makes sure the example still compiles

sdk/agent/agent.go, sdk/state/payment.go, sdk/state/payment_test.go
Add a memo field to close agreements that is optional. The memo is a string with unspecified bounds. The memo is not included in the final transaction so its contents does not leak to the public ledger when the channel is closed. Subsequently the signatures for close agreements to do not cover the memo.
Payments should have memos so they can be identifiable on the terms of the participants. Participants may communicate about a payment ahead of sending a payment and the memo will provide a way to annotate or identify the payment in whatever way they require.
Note that this is similar but different to #339. #339 is concerned with uniquely identifying payments with an identifier that the state machine attaches to close agreements. That would not be useful in the situation described above …
=> sdk/state, sdk/agent: add memos to payments

.github/workflows/examples-benchmark.yml, .github/workflows/examples-console.yml, .github/workflows/sdk.yml
Pin the version of the golangci-lint action to a specific commit.
So that we don't introduce new action code into our builds without us knowing about it and choosing to explicitly do that.
It is a good practice noted here: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
=> all: pin golangci-lint action version

.github/workflows/sdk.yml, Getting Started.md, README.md, examples/benchmark/go.mod, examples/benchmark/go.sum, examples/bufferedbenchmark/go.mod, examples/bufferedbenchmark/go.sum, examples/console/go.mod, examples/console/go.sum, sdk/go.mod, sdk/go.sum
Update the URLs and imports for the Go SDK and the Quickstart forks.
I'm moving all the forks, that live on branches of my forks of the respective repos, to branches on the source repos to facilitate smoother collaboration. This should be no functional change.
=> all: update urls to gosdk and quickstart forks

examples/benchmark/go.mod, examples/benchmark/go.sum, examples/bufferedbenchmark/go.mod, examples/bufferedbenchmark/go.sum, examples/console/go.mod, examples/console/go.sum, sdk/go.mod, sdk/go.sum, sdk/state/asset.go, sdk/state/ingest.go, sdk/state/ingest_test.go, sdk/state/integrationtests/helpers_test.go, sdk/txbuild/create_escrow.go, sdk/txbuild/formation.go, sdk/txbuildtest/txbuildtest.go
**WHAT**
updates the go-sdk dependency to the[ updated branch](https://github.com/stellar/go/tree/cap21and40) we have on the stellar/go repo now
**WHY**
updating the go-sdk with the protocol 18 changes, and updating our sdk since it depends on it
=> all: update stellar/go dependency to use updated with protocol 18 branch

sdk/agent/agent.go, sdk/msg/msg.go, sdk/state/state.go
Make responses compact by reducing them down to only the signatures that need returning to the proposer.
The message format and agent is implemented such that the confirmer passes back the full close envelope back to the proposer. It was done this way because we planned to possibly support things like [merging channels](https://github.com/stellar/starlight/discussions/330#discussioncomment-1345289) which requires clearly identifying confirmations. Close envelopes were never that big, so we didn't worry about this too much.
However, since we implemented [buffered channel](https://github.com/stellar/starlight/discussions/330#discussioncomment-1345257) the close envelope now contains information about all the buffered payments that are summarized in the memo of the channel's payment. Sending …
=> sdk/msg, sdk/agent: make responses compact

examples/console/main.go
Change how amounts are chosen when running a benchmark so that the amount isn't modified to negative.
I recently changed how amounts are determined so that the amounts are not uniform and don't use a pseudorandom generator. However the change I made caused amounts to go negative. This should fix that.
=> examples/console: fix small amounts

examples/dashboard.html
Poll for new state once every 100ms instead of 5-6 times every 100ms.
The dashboard is putting load on the console example to the point where it is creating contention on the internal mutexes when getting the snapshot, and this impacts the performance of the demo.
=> examples/dashboard: poll for new state less frequently

examples/console/README.md
**WHAT**
updates the example/console README. Things noticed while working on https://github.com/stellar/starlight/pull/403
**WHY**
we removed the need of passing in an account when starting the app but the README still recommends it. the -account flag isn't supported and the -signer flag isn't required now.
also adds the `declareclose` command which is the recommended way to close the channel.
=> examples/console: update README

sdk/agent/agent.go, sdk/state/doc.go, sdk/state/payment.go, sdk/state/payment_test.go
Add a finalize payment function that a payment proposer can use to finalize a payment when the confirmer sends back their signatures.
Today this functionality is provided by the `ConfirmPayment` function that is used by both the proposer and the confirmer. Because it is used by both it accepts a full close agreement envelope and does a lot of validation of the contents. The proposer gets back the signatures from the confirmer and doesn't actually need to verify the agreement. They just need to attach the signatures and see if they're valid. That's what the finalize payment function does.
This change has no material performance improvement. I attempted the change to see if it improved performance and it did not in a meaningful way. Reflecting on it though, this does feel like it naturally …
=> sdk/state, sdk/agent: finalize payment

specifications/starlight-payment-channel-mechanics.md
**WHAT**
updates the SEP to use the term multisig instead of escrow.
**WHY**
escrow implies the use of a third party, which is not what the accounts in the payment channels are. Using MultiSig instead makes it clearer what the account's purpose in the payment channel process is.
as part of #371 
this PR is changing the SEP. The code changes will be done in: https://github.com/stellar/starlight/pull/408
=> sep: change sep to use multisig term instead of escrow

examples/console/main.go
When 'other' is included in the deposit command as the second parameter, have the deposit go to the other participant.
This is how the deposit used to work, but a bug was introduced recently which prevented us from following the code path where the deposit was directed to the other participant.
=> examples/console: fix deposits to other

examples/benchmark/go.mod, examples/benchmark/go.sum, examples/bufferedbenchmark/go.mod, examples/bufferedbenchmark/go.sum, examples/console/go.mod, examples/console/go.sum, sdk/go.mod, sdk/go.sum
Update the stellar/go dependency to use the latest commit of the cap21and40 branch.
The latest commit contains updates to the version of go-xdr that is used that provides more efficient transaction encoding and decoding. It also contains updated XDR.
=> all: update to use latest stellar/go branch

specifications/starlight-payment-channel-mechanics.md
Add link to the prototype implementation in the specification.
We have a section there for it, may as well link to it.
=> doc: add link to starlight implementation

Getting Started.md
Remove the doc entry that demonstrates accelerating time of the Core network.
It's useful for development, but sort of adds more text to the docs that is unnecessary and makes it harder to understand and digest the getting started.
=> doc: remove enable accelerate time

sdk/agent/agent.go, sdk/agent/tcp.go
Add some docs to the sdk/agentpackage.
Most types and functions were documented, but some were missing, and this fills the gaps.
=> sdk/agent: add docs

sdk/agent/horizon/balance_collector.go, sdk/agent/horizon/doc.go, sdk/agent/horizon/sequence_number_collector.go, sdk/agent/horizon/streamer.go, sdk/agent/horizon/submitter.go, sdk/agent/submit/submitter.go
Add some docs to the sdk/agent/horizon package.
To communicate the intent of the package.
=> sdk/agent/horizon: add docs

sdk/agent/msg/msg.go
Add some docs to the sdk/agent/msg package.
To communicate the intent of the package, and the compatibility guarantees, or lack of, within.
=> sdk/agent/msg: add docs

sdk/agent/submit/submitter.go
Add some docs to the sdk/agent/submit package.
To communicate the intent of the package.
=> sdk/agent/submit: add docs

sdk/agent/agenthttp/agenthttp.go
Add some docs to the sdk/agent/agenthttp package.
To communicate the intent of the package.
=> sdk/agent/agenthttp: add docs

sdk/agent/bufferedagent/agent.go, sdk/agent/bufferedagent/buffered_payment.go, sdk/agent/bufferedagent/tcp.go
Add some docs to the sdk/agent/bufferedagent package.
To communicate the intent of the package, and the compatibility guarantees, or lack of, within.
=> sdk/agent/bufferedagent: add docs

examples/console/main.go
Add support for deployed environments with a friendbot for creating the accounts in the console application.
To make the console application compatible with deployed environments where there is a friendbot for creating new test accounts.
=> examples/console: support friendbot for deployed environments

sdk/state/integrationtests/state_test.go, sdk/state/payment.go, sdk/state/state.go
Unexport the NextIterationNumber method of the Channel type.
It's dubious why a consumer of the package would need this function. If anything it exposes a little too much about the internals of the package. It may actually be difficult to use the function correctly or to fully understand why it returned the number it returned. In some cases it returns the current iteration, other times the next, depending on state and what is happening. This is because it always returns the iteration number of the next authorized transaction but that is counter intuitive when a participant has proposed a new payment because that payment is unauthorized. Unexporting the function removes this complexity from the packages surface API.
The only place it is used outside the package is in the integration tests, …
=> sdk/state: unexport Channel.NextIterationNumber

Getting Started.md
Update the getting started docs to reference the docker image published to docker.io.
The getting started docs show how to build the image, but building the image is unnecessary as it is now published to docker.io.
=> Update docs to reference docker image on docker.io

specifications/starlight-payment-channel-mechanics.md
Add discussion about the presence of a free-option in multi-party protocols.
@jonjove highlighted the presence of a free-option in payment channel protocols. This is not unique to Starlight and plagues many multi-party protocols, especially payment channel protocols.
Given that Starlight is a single-asset payment channel protocol at this time the ability to exploit this is limited to free-options with off-chain value that is being exchanged with value captured in the payment channel.
Related to https://github.com/stellar/stellar-protocol/pull/1150
=> doc: add discussion about the presence of a free-option

.github/workflows/examples-benchmark.yml, .github/workflows/examples-bufferedbenchmark.yml, .github/workflows/examples-console.yml, .github/workflows/sdk.yml, examples/benchmark/go.mod, examples/benchmark/go.sum, examples/bufferedbenchmark/go.mod, examples/bufferedbenchmark/go.sum, examples/console/go.mod, examples/console/go.sum, go.work, go.work.sum, sdk/go.mod, sdk/go.sum
Move compatibility to Go 1.18 and use go.work.
Go.work was added in Go 1.18 and makes it easier to work in repos that have multiple go.mod files. This repo has always maintained compatibility only with the most recent version of Go, so moving compat to Go 1.18 is fine as it is the latest version.
=> all: move compat to go118 and use go.work

.github/workflows/sdk.yml, Getting Started.md, README.md
Update instructions for running the examples and docker image. Remove instructions for the devnet.
###
The instructions are out of date now that Horizon and Stellar-Core have released RCs. The devnet is out of date. It'll be updated in https://github.com/stellar/ops/issues/1674, but in the meantime remove the instructions.
=> docs: update instructions for running

examples/console/main.go
Add log for when close occurs that is outdated.
Helpful for debugging.
=> examples/console: add log for when close occurs that is outdated

.github/workflows/sdk.yml, Getting Started.md, README.md, examples/console/README.md, examples/console/main.go, examples/dashboard.html, sdk/state/integrationtests/main_test.go
Update the docs and integration tests to run against testnet by default, but still run the CI integration tests against quickstart.
It's all on testnet now.
=> all: update test env to testnet
